#!/usr/bin/env python3
"""Self-hosts each concept's Google Fonts (latin + latin-ext woff2) and writes assets/css/fonts.css.
Run from the project root: python tools/fonts.py   (uses curl for the downloads)"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
FAMILIES = {
    'site-a-kali-nak-lagi': ['Anton', 'Rubik:ital,wght@0,300..800;1,300..800', 'Caveat+Brush'],
    'site-b-jagung-rangup': ['Archivo:wdth,wght@62..125,100..900', 'Geist:wght@100..900', 'Geist+Mono:wght@100..900'],
}
KEEP = {'latin', 'latin-ext'}


def get(url, binary=False):
    out = subprocess.run(['curl', '-sSL', '--max-time', '60', '-A', UA, url], check=True, capture_output=True)
    return out.stdout if binary else out.stdout.decode('utf-8')


def main():
    for site, families in FAMILIES.items():
        fonts_dir = ROOT / site / 'assets' / 'fonts'
        fonts_dir.mkdir(parents=True, exist_ok=True)
        css_out = []
        for fam in families:
            css = get(f'https://fonts.googleapis.com/css2?family={fam}&display=swap')
            for subset, block in re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})', css):
                if subset not in KEEP:
                    continue
                url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
                name = re.search(r"font-family:\s*'([^']+)'", block).group(1)
                style = re.search(r'font-style:\s*(\w+)', block).group(1)
                file = f"{name.lower().replace(' ', '-')}-{style}-{subset}.woff2"
                (fonts_dir / file).write_bytes(get(url, binary=True))
                css_out.append(block.replace(url, f'../fonts/{file}'))
        dest = ROOT / site / 'assets' / 'css' / 'fonts.css'
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text('/* Self-hosted Google Fonts (SIL Open Font License). Generated by tools/fonts.py */\n'
                        + '\n'.join(css_out) + '\n', encoding='utf-8')
        print(site, len(css_out), 'faces')


if __name__ == '__main__':
    main()
